name: primeiro-workflow # Nome tecnico
run name: Meu Primeiro Workflow # Nome descritivo

# on: [push]

# event 
on:

    push:
        branches: 
            - main

jobs: 
    mac:
        runs-on: macos-latest
        steps:
            - name: Rodar um hello no mac
              run: echo "Rodou no mac"